//This file was created via CT-GUI! Editing it is not advised!
//Don't touch me!
//#Remove
//Don't touch me!
//#Add
recipes.addShaped(<thermalinnovation:injector:32000>, [[<extrautils2:passivegenerator:3>, <botania:blackholetalisman>, <extrautils2:passivegenerator:3>],[<appliedenergistics2:material:47>, <thermalinnovation:injector>, <appliedenergistics2:material:47>], [<minecraft:dragon_egg>, <extrautils2:machine>, <minecraft:dragon_egg>]]);
recipes.addShaped(<bloodmagic:activation_crystal:2>, [[<bloodarsenal:blood_diamond:2>, <bloodmagic:soul_gem:4>, <bloodarsenal:blood_diamond:2>],[<bloodarsenal:blood_diamond:2>, <bloodmagic:blood_orb>.withTag({orb: "bloodmagic:archmage"}), <bloodarsenal:blood_diamond:2>], [<minecraft:dragon_egg>, <minecraft:dragon_egg>, <minecraft:dragon_egg>]]);
recipes.addShaped(<botania:manatablet>.withTag({mana: 500000, creative: 1 as byte}), [[<botanicadds:gaiasteel_block>, <botania:blackholetalisman>, <botanicadds:gaiasteel_block>],[<botanicadds:gaiasteel_block>, <botanicadds:ring_aura_gaia>, <botanicadds:gaiasteel_block>], [<minecraft:dragon_egg>, <minecraft:dragon_egg>, <minecraft:dragon_egg>]]);
recipes.addShaped(<ae2wtlib:wut_creative>, [[<appliedenergistics2:quantum_ring>, <ae2wtlib:wut>, <appliedenergistics2:quantum_ring>],[<appliedenergistics2:quantum_ring>, <minecraft:dragon_egg>, <appliedenergistics2:quantum_ring>], [<appliedenergistics2:quantum_ring>, <extrautils2:passivegenerator:8>, <appliedenergistics2:quantum_ring>]]);
recipes.addShaped(<minecraft:dragon_egg> * 2, [[<minecraft:elytra>, <minecraft:elytra>, <minecraft:elytra>],[<icbmclassic:explosives:23>, <minecraft:dragon_egg>, <icbmclassic:explosives:23>], [<minecraft:elytra>, <minecraft:elytra>, <minecraft:elytra>]]);
recipes.addShaped(<botania:odinring> * 2, [[null, <botanicadds:ring_aura_gaia>, null],[null, <minecraft:dragon_egg>, null], [null, <botanicadds:ring_aura_gaia>, null]]);
recipes.addShaped(<compactvoidminers:void_miner> * 2, [[<enderio:item_alloy_ingot:6>, <minecraft:dragon_egg>, <enderio:item_alloy_ingot:6>],[<enderio:item_alloy_ingot:6>, <appliedenergistics2:quantum_link>, <enderio:item_alloy_ingot:6>], [<enderio:item_alloy_ingot:6>, <industrialforegoing:laser_drill>, <enderio:item_alloy_ingot:6>]]);
recipes.addShaped(<witchery:warm_blood>, [[<witchery:vampiric_poppet>, <xreliquary:angelheart_vial>, null],[<botania:vial:1>, <xreliquary:angelheart_vial>, null], [<witchery:blood_poppy>, <xreliquary:angelheart_vial>, null]]);
recipes.addShaped(<witchery:warm_blood>, [[<witchery:death_protection_poppet>, null, null],[<botania:vial:1>, null, null], [<witchery:blood_poppy>, null, null]]);
recipes.addShaped(<extrautils2:chunkloader>, [[<xreliquary:salamander_eye>, <minecraft:dragon_egg>, <witchery:otherwhere_spirit>],[null, <witchery:scarecrow>, null], [null, <botania:manaresource:3>, null]]);
recipes.addShaped(<portalgun:item_portalgun>, [[<computercraft:pocket_computer:1>, <mekanism:atomicdisassembler>, null],[<enderio:item_alloy_ingot>, <plethora:module:1>, <botania:blackholetalisman>], [null, null, <enderio:item_alloy_ingot>]]);
recipes.addShaped(<extrautils2:teleporter:1>, [[<extrautils2:compressedcobblestone:6>, <extrautils2:compressedcobblestone:6>, <extrautils2:compressedcobblestone:6>],[<extrautils2:compressedcobblestone:6>, <extrautils2:interactionproxy>, <extrautils2:compressedcobblestone:6>], [<extrautils2:compressedcobblestone:6>, <extrautils2:compressedcobblestone:6>, <extrautils2:compressedcobblestone:6>]]);
recipes.addShaped(<extrautils2:quarryproxy>, [[<ic2:iridium_reflector>, <openmodularturrets:turret_base:4>, <extrautils2:teleporter:1>],[<openmodularturrets:turret_base:4>, <industrialforegoing:laser_drill>, <appliedenergistics2:material:47>], [<ic2:iridium_reflector>, <openmodularturrets:turret_base:4>, <extrautils2:teleporter:1>]]);
recipes.addShaped(<extrautils2:quarry>, [[<industrialforegoing:laser_base>, <extrautils2:snowglobe:1>, <environmentaltech:structure_frame_5>],[<appliedenergistics2:quantum_link>, <mekanism:machineblock:4>, <appliedenergistics2:quantum_link>], [<environmentaltech:structure_frame_5>, <mekanism:machineblock:4>, <industrialforegoing:laser_base>]]);
recipes.addShaped(<environmentaltech:void_ore_miner_cont_6>, [[<environmentaltech:aethium>, <extrautils2:quarry>, <environmentaltech:aethium>],[<environmentaltech:aethium>, <environmentaltech:void_ore_miner_cont_5>, <environmentaltech:aethium>], [<environmentaltech:aethium>, <gravisuite:vajra:26>, <environmentaltech:aethium>]]);
recipes.addShaped(<environmentaltech:void_ore_miner_cont_5>, [[<environmentaltech:ionite>, <minecraft:elytra>, <environmentaltech:ionite>],[<environmentaltech:ionite>, <environmentaltech:void_ore_miner_cont_4>, <environmentaltech:ionite>], [<environmentaltech:ionite>, <bhc:blue_heart>, <environmentaltech:ionite>]]);
recipes.addShaped(<environmentaltech:void_ore_miner_cont_4>, [[<environmentaltech:pladium>, <openmodularturrets:turret_base:4>, <environmentaltech:pladium>],[<environmentaltech:pladium>, <environmentaltech:void_ore_miner_cont_3>, <environmentaltech:pladium>], [<environmentaltech:pladium>, <mekanism:machineblock:4>, <environmentaltech:pladium>]]);
recipes.addShaped(<environmentaltech:void_ore_miner_cont_3>, [[<environmentaltech:kyronite>, <simplyjetpacks:metaitemmods:38>, <environmentaltech:kyronite>],[<environmentaltech:kyronite>, <environmentaltech:void_ore_miner_cont_2>, <environmentaltech:kyronite>], [<environmentaltech:kyronite>, <industrialforegoing:infinity_drill>, <environmentaltech:kyronite>]]);
recipes.addShaped(<environmentaltech:void_ore_miner_cont_2>, [[<environmentaltech:erodium>, <extrautils2:snowglobe:1>, <environmentaltech:erodium>],[<environmentaltech:erodium>, <environmentaltech:void_ore_miner_cont_1>, <environmentaltech:erodium>], [<environmentaltech:erodium>, <minecraft:beacon>, <environmentaltech:erodium>]]);
recipes.addShaped(<environmentaltech:void_ore_miner_cont_1>, [[<environmentaltech:interconnect>, <industrialforegoing:laser_drill>, <environmentaltech:interconnect>],[<environmentaltech:litherite>, <industrialforegoing:laser_base>, <environmentaltech:litherite>], [<enderio:item_material:1>, <mekanism:machineblock3>, <enderio:item_material:1>]]);
recipes.addShaped(<environmentaltech:structure_frame_6>, [[<ic2:lapotron_crystal:26>, <extrautils2:compressedcobblestone:7>, <ic2:lapotron_crystal:26>],[<environmentaltech:aethium_crystal>, <environmentaltech:structure_frame_5>, <environmentaltech:aethium_crystal>], [<minecraft:dragon_breath>, <openmodularturrets:turret_base:4>, <minecraft:dragon_breath>]]);
recipes.addShaped(<environmentaltech:structure_frame_5>, [[null, <openmodularturrets:turret_base:3>, null],[<simplyjetpacks:metaitemmods:19>, <environmentaltech:structure_frame_4>, <simplyjetpacks:metaitemmods:19>], [<minecraft:nether_star>, <environmentaltech:ionite_crystal>, <minecraft:nether_star>]]);
recipes.addShaped(<environmentaltech:structure_frame_4>, [[<minecraft:black_shulker_box>, <ic2:energy_crystal:26>, <minecraft:black_shulker_box>],[<environmentaltech:pladium_crystal>, <environmentaltech:structure_frame_3>, <environmentaltech:pladium_crystal>], [<minecraft:black_shulker_box>, <thermalfoundation:upgrade:3>, <minecraft:black_shulker_box>]]);
recipes.addShaped(<environmentaltech:structure_frame_3>, [[<thermalfoundation:material:1025>, <minecraft:diamond_block>, <thermalfoundation:material:1025>],[<environmentaltech:kyronite_crystal>, <environmentaltech:structure_frame_2>, <environmentaltech:kyronite_crystal>], [<thermalfoundation:material:1025>, <thermalfoundation:upgrade:2>, <thermalfoundation:material:1025>]]);
recipes.addShaped(<environmentaltech:structure_frame_2>, [[<enderio:item_alloy_ingot:6>, <environmentaltech:erodium_crystal>, <thermalfoundation:material:515>],[<mekanism:atomicalloy>, <environmentaltech:structure_frame_1>, <mekanism:atomicalloy>], [<thermalfoundation:material:515>, <environmentaltech:erodium_crystal>, <enderio:item_alloy_ingot:6>]]);
recipes.addShaped(<environmentaltech:structure_frame_1>, [[null, <redstonearsenal:material:128>, null],[<environmentaltech:litherite>, <enderio:item_material:1>, <environmentaltech:litherite>], [null, <redstonearsenal:material:128>, null]]);
recipes.addShaped(<mekanismgenerators:reactor:1>, [[null, <mekanism:basicblock:8>, null],[<mekanism:basicblock:8>, <pneumaticcraft:printed_circuit_board>, <mekanism:basicblock:8>], [null, <mekanism:basicblock:8>, null]]);
recipes.addShaped(<bigreactors:reactorcasing>, [[<bigreactors:ingotgraphite>, <bigreactors:ingotgraphite>, <bigreactors:ingotgraphite>],[<bigreactors:ingotgraphite>, <ic2:resource:13>, <bigreactors:ingotgraphite>], [<bigreactors:ingotgraphite>, <bigreactors:ingotgraphite>, <bigreactors:ingotgraphite>]]);
recipes.addShaped(<plethora:module:3>, [[null, <icbmclassic:radarstation>, null],[null, <computercraft:computer>, null], [null, null, null]]);
recipes.addShaped(<mekanism:basicblock:8>, [[<thermalfoundation:material:160>, <thermalfoundation:storage_alloy>, <thermalfoundation:material:160>],[<minecraft:iron_bars>, <ic2:resource:13>, <minecraft:iron_bars>], [<thermalfoundation:material:160>, <thermalexpansion:cell>, <thermalfoundation:material:160>]]);
recipes.addShaped(<enderio:item_material>, [[<enderio:block_dark_iron_bars>, <thermalfoundation:material:130>, <enderio:block_dark_iron_bars>],[<enderio:item_material:11>, <ic2:resource:13>, <enderio:item_material:11>], [<enderio:block_dark_iron_bars>, <thermalexpansion:cell>, <enderio:block_dark_iron_bars>]]);
recipes.addShaped(<thermalexpansion:frame>, [[<minecraft:glass>, <minecraft:glass>, <minecraft:glass>],[<thermaldynamics:duct_0>, <ic2:resource:12>, <thermaldynamics:duct_0>], [<thermalfoundation:material:257>, <thermalexpansion:cell>, <thermalfoundation:material:257>]]);
recipes.addShaped(<ic2:resource:13>, [[<ic2:crafting:15>, <ic2:crafting:3>, <ic2:crafting:15>],[<enderio:item_basic_capacitor>, <ic2:resource:12>, <enderio:item_basic_capacitor>], [<ic2:crafting:15>, <ic2:crafting:3>, <ic2:crafting:15>]]);
//recipes.addShaped(<compactvoidminers:void_miner>, [[<enderio:item_material:66>, <extrautils2:snowglobe:1>, <enderio:item_material:66>],[<mekanism:basicblock2:3>.withTag({tier: 3}), <industrialforegoing:laser_drill>, <mekanism:basicblock2:4>.withTag({tier: 3})], [<computercraft:pocket_computer:1>.withTag({upgrade: "plethora:sensor"}), <mekanism:machineblock:4>, <pneumaticcraft:printed_circuit_board>]]);
recipes.addShapeless(<bhc:red_heart_canister>, [<bhc:red_heart>,<bhc:wither_bone>,<thermalfoundation:material:134>,<bhc:canister>]);
recipes.addShapeless(<bhc:yellow_heart_canister>, [<botania:manaresource:4>, <bhc:yellow_heart>,<minecraft:golden_apple:1>, <bhc:red_heart_canister>]);
recipes.addShapeless(<bhc:blue_heart_canister>, [<witchery:leonards_urn1>, <xreliquary:witherless_rose>, <bhc:blue_heart>, <bhc:green_heart_canister>]);
recipes.addShapeless(<bhc:green_heart_canister>, [<minecraft:nether_star>,<witchery:redstone_soup>,<bhc:green_heart>,<bhc:yellow_heart_canister>]);
recipes.addShaped(<xreliquary:angelheart_vial>, [[null, <xreliquary:witherless_rose>, <witchery:demonic_blood>],[null, <botania:brewvial>.withTag({brewKey: "healing"}), <botania:manaresource:14>], [null, <minecraft:golden_apple:1>, <witchery:flowing_spirit_brew>]]);
recipes.addShapeless(<xreliquary:phoenix_down>, [<xreliquary:angelheart_vial>,<xreliquary:angelheart_vial>,<xreliquary:angelic_feather>,<minecraft:end_crystal>,<minecraft:end_crystal>,<minecraft:end_crystal>]);
recipes.addShaped(<xreliquary:angelheart_vial>, [[<xreliquary:mob_ingredient:9>, <extrautils2:angelring>, <xreliquary:mob_ingredient:9>],[<minecraft:golden_apple:1>, <botania:brewvial>.withTag({brewKey: "healing"}), <industrialforegoing:pink_slime>], [null, <xreliquary:salamander_eye>, null]]);
recipes.addShaped(<witchery:death_protection_poppet>, [[<witchery:charged_attuned_stone>, <witchery:luck_drop>, <witchery:charged_attuned_stone>],[<witchery:charged_attuned_stone>, <witchery:poppet>, <witchery:charged_attuned_stone>], [null, <xreliquary:phoenix_down>, null]]);
recipes.addShaped(<witchery:vampiric_poppet>, [[<witchery:bat_wool>, <witchery:bat_wool>, <witchery:bat_wool>],[<witchery:creeper_heart>, <witchery:poppet>, <witchery:creeper_heart>], [<witchery:charged_attuned_stone>, <witchery:demon_heart>, <witchery:charged_attuned_stone>]]);
recipes.addShaped(<icbmclassic:explosives:23>, [[<extrautils2:compressedcobblestone:7>, <minecraft:elytra>, <extrautils2:compressedcobblestone:7>],[<icbmclassic:explosives:22>, <botania:manaresource:15>, <icbmclassic:explosives:22>], [<extrautils2:compressedcobblestone:7>, <icbmclassic:explosives:22>, <extrautils2:compressedcobblestone:7>]]);
recipes.addShaped(<icbmclassic:explosives:22>, [[<mekanism:basicblock2:3>.withTag({tier: 3}), <mekanism:basicblock2:3>.withTag({tier: 3}), <mekanism:basicblock2:3>.withTag({tier: 3})],[<mekanism:basicblock2:3>.withTag({tier: 3}), <icbmclassic:explosives:15>, <mekanism:basicblock2:3>.withTag({tier: 3})], [<mekanism:basicblock2:3>.withTag({tier: 3}), <mekanism:basicblock2:3>.withTag({tier: 3}), <mekanism:basicblock2:3>.withTag({tier: 3})]]);
recipes.addShaped(<icbmclassic:explosives:15>, [[<icbmclassic:explosives:13>, <computercraft:computer>, <icbmclassic:explosives:13>],[<minecraft:nether_star>, <ic2:te:22>, <minecraft:nether_star>], [<appliedenergistics2:material:47>, <extrautils2:unstableingots>, <appliedenergistics2:material:47>]]);
recipes.addShaped(<industrialforegoing:mob_duplicator>, [[<industrialforegoing:pink_slime_ingot>, <enderio:block_experience_obelisk>, <industrialforegoing:pink_slime_ingot>],[<mekanism:basicblock2:4>.withTag({tier: 3}), <extrautils2:compressedcobblestone:5>, <mekanism:basicblock2:3>.withTag({tier: 2})], [<enderio:item_material:55>, <enderio:block_dark_steel_anvil>, <enderio:item_material:55>]]);
recipes.addShaped(<enderio:block_powered_spawner>, [[<openmodularturrets:turret_base:4>, <enderio:item_material:55>, <openmodularturrets:turret_base:4>],[<enderio:item_material:41>, <industrialforegoing:mob_duplicator>, <minecraft:elytra>], [<witchery:flowing_spirit_brew>, <industrialforegoing:mob_duplicator>, <witchery:flowing_spirit_brew>]]);
recipes.addShaped(<gravisuite:vajra>, [[<appliedenergistics2:controller>, <appliedenergistics2:material:38>, <appliedenergistics2:material:38>],[<appliedenergistics2:dense_energy_cell>, <botania:lens:6>, <ic2:energy_crystal>], [<mekanism:atomicdisassembler>, <powersuits:power_fist>, <gravisuite:crafting:5>]]);
recipes.addShaped(<mekanism:atomicdisassembler>, [[<redstonearsenal:tool.pickaxe_flux>, <mekanism:energycube>.withTag({tier: 3}), <redstonearsenal:tool.sword_flux>],[<redstonearsenal:tool.shovel_flux>, <enderio:item_material:73>, <redstonearsenal:tool.axe_flux>], [<simplyjetpacks:metaitemmods:12>, <enderio:item_material:54>, <simplyjetpacks:metaitemmods:12>]]);
recipes.addShaped(<extrautils2:angelring>, [[<botania:pylon:2>, <witchery:subdued_spirit>, <botania:pylon:2>],[<extrautils2:unstableingots>, <botania:pixiering>, <extrautils2:unstableingots>], [null, <botania:rune:3>, null]]);
recipes.addShaped(<enderio:block_tele_pad>, [[<mekanism:machineblock:11>, <openmodularturrets:turret_base:4>, <mekanism:machineblock:11>],[<enderio:item_material:54>, <computercraft:computer:16384>, <enderio:item_material:54>], [<mekanism:basicblock:8>, <ic2:te:39>, <mekanism:basicblock:8>]]);
recipes.addShaped(<industrialforegoing:laser_base>, [[<appliedenergistics2:material:38>, <mekanism:energycube>.withTag({tier: 3}), <thermaldynamics:duct_0:5>],[<enderio:item_material:54>, <mekanism:machineblock2:14>, <enderio:item_material:54>], [<simplyjetpacks:metaitemmods:23>, <openmodularturrets:turret_base:3>, <simplyjetpacks:metaitemmods:23>]]);
recipes.addShaped(<industrialforegoing:laser_drill>, [[<enderio:item_material:53>, <thermalfoundation:upgrade:3>, <mekanism:transmitter:6>],[<simplyjetpacks:itemfluxpack:9>, <redstonearsenal:tool.pickaxe_flux>, <mekanism:machineblock2:13>], [<enderio:item_material:54>, <mekanism:machineblock3>, <mekanism:transmitter>]]);
recipes.addShaped(<mekanism:machineblock:4>, [[<enderio:block_dark_steel_anvil>, <appliedenergistics2:material:47>, <enderio:block_dark_steel_anvil>],[<mekanism:basicblock2:4>.withTag({tier: 3}), <appliedenergistics2:material:38>, <mekanism:basicblock2:3>.withTag({tier: 3})], [<thermalinnovation:saw:4>, <mekanism:machineblock3>, <thermalinnovation:drill:4>]]);
//File End
