//This file was created via CT-GUI! Editing it is not advised!
//Don't touch me!
//#Remove
//Don't touch me!
//#Add
recipes.addShaped(<mekanismgenerators:reactor:1>, [[null, <mekanism:basicblock:8>, null],[<mekanism:basicblock:8>, <pneumaticcraft:printed_circuit_board>, <mekanism:basicblock:8>], [null, <mekanism:basicblock:8>, null]]);
recipes.addShaped(<bigreactors:reactorcasing>, [[<bigreactors:ingotgraphite>, <bigreactors:ingotgraphite>, <bigreactors:ingotgraphite>],[<bigreactors:ingotgraphite>, <ic2:resource:13>, <bigreactors:ingotgraphite>], [<bigreactors:ingotgraphite>, <bigreactors:ingotgraphite>, <bigreactors:ingotgraphite>]]);
recipes.addShaped(<plethora:module:3>, [[null, <icbmclassic:radarstation>, null],[null, <computercraft:computer>, null], [null, null, null]]);
recipes.addShaped(<mekanism:basicblock:8>, [[<thermalfoundation:material:160>, <thermalfoundation:storage_alloy>, <thermalfoundation:material:160>],[<minecraft:iron_bars>, <ic2:resource:13>, <minecraft:iron_bars>], [<thermalfoundation:material:160>, <thermalexpansion:cell>, <thermalfoundation:material:160>]]);
recipes.addShaped(<enderio:item_material>, [[<enderio:block_dark_iron_bars>, <thermalfoundation:material:130>, <enderio:block_dark_iron_bars>],[<enderio:item_material:11>, <ic2:resource:13>, <enderio:item_material:11>], [<enderio:block_dark_iron_bars>, <thermalexpansion:cell>, <enderio:block_dark_iron_bars>]]);
recipes.addShaped(<thermalexpansion:frame>, [[<minecraft:glass>, <minecraft:glass>, <minecraft:glass>],[<thermaldynamics:duct_0>, <ic2:resource:12>, <thermaldynamics:duct_0>], [<thermalfoundation:material:257>, <thermalexpansion:cell>, <thermalfoundation:material:257>]]);
recipes.addShaped(<ic2:resource:13>, [[<ic2:crafting:15>, <ic2:crafting:3>, <ic2:crafting:15>],[<enderio:item_basic_capacitor>, <ic2:resource:12>, <enderio:item_basic_capacitor>], [<ic2:crafting:15>, <ic2:crafting:3>, <ic2:crafting:15>]]);
recipes.addShaped(<compactvoidminers:void_miner>, [[<enderio:item_material:66>, <extrautils2:snowglobe:1>, <enderio:item_material:66>],[<mekanism:basicblock2:3>.withTag({tier: 3}), <industrialforegoing:laser_drill>, <mekanism:basicblock2:4>.withTag({tier: 3})], [<computercraft:pocket_computer:1>.withTag({upgrade: "plethora:sensor"}), <mekanism:machineblock:4>, <pneumaticcraft:printed_circuit_board>]]);
recipes.addShapeless(<bhc:red_heart_canister>, [<bhc:red_heart>,<bhc:wither_bone>,<thermalfoundation:material:134>,<bhc:canister>]);
recipes.addShapeless(<bhc:yellow_heart_canister>, [<botania:manaresource:4>, <bhc:yellow_heart>,<minecraft:golden_apple:1>, <bhc:red_heart_canister>]);
recipes.addShapeless(<bhc:blue_heart_canister>, [<witchery:leonards_urn1>, <xreliquary:witherless_rose>, <bhc:blue_heart>, <bhc:green_heart_canister>]);
recipes.addShapeless(<bhc:green_heart_canister>, [<minecraft:nether_star>,<witchery:redstone_soup>,<bhc:green_heart>,<bhc:yellow_heart_canister>]);
recipes.addShaped(<xreliquary:angelheart_vial>, [[null, <xreliquary:witherless_rose>, <witchery:demonic_blood>],[null, <botania:brewvial>.withTag({brewKey: "healing"}), <botania:manaresource:14>], [null, <minecraft:golden_apple:1>, <witchery:flowing_spirit_brew>]]);
recipes.addShapeless(<xreliquary:phoenix_down>, [<xreliquary:angelheart_vial>,<xreliquary:angelheart_vial>,<xreliquary:angelic_feather>,<minecraft:end_crystal>,<minecraft:end_crystal>,<minecraft:end_crystal>]);
recipes.addShaped(<xreliquary:angelheart_vial>, [[<xreliquary:mob_ingredient:9>, <extrautils2:angelring>, <xreliquary:mob_ingredient:9>],[<minecraft:golden_apple:1>, <botania:brewvial>.withTag({brewKey: "healing"}), <industrialforegoing:pink_slime>], [null, <xreliquary:salamander_eye>, null]]);
recipes.addShaped(<witchery:death_protection_poppet>, [[<witchery:charged_attuned_stone>, <witchery:luck_drop>, <witchery:charged_attuned_stone>],[<witchery:charged_attuned_stone>, <witchery:poppet>, <witchery:charged_attuned_stone>], [null, <xreliquary:phoenix_down>, null]]);
recipes.addShaped(<witchery:vampiric_poppet>, [[<witchery:bat_wool>, <witchery:bat_wool>, <witchery:bat_wool>],[<witchery:creeper_heart>, <witchery:poppet>, <witchery:creeper_heart>], [<witchery:charged_attuned_stone>, <witchery:demon_heart>, <witchery:charged_attuned_stone>]]);
recipes.addShaped(<icbmclassic:explosives:23>, [[<extrautils2:compressedcobblestone:7>, <minecraft:elytra>, <extrautils2:compressedcobblestone:7>],[<icbmclassic:explosives:22>, <botania:manaresource:15>, <icbmclassic:explosives:22>], [<extrautils2:compressedcobblestone:7>, <icbmclassic:explosives:22>, <extrautils2:compressedcobblestone:7>]]);
recipes.addShaped(<icbmclassic:explosives:22>, [[<mekanism:basicblock2:3>.withTag({tier: 3}), <mekanism:basicblock2:3>.withTag({tier: 3}), <mekanism:basicblock2:3>.withTag({tier: 3})],[<mekanism:basicblock2:3>, <icbmclassic:explosives:15>, <mekanism:basicblock2:3>.withTag({tier: 3})], [<mekanism:basicblock2:3>.withTag({tier: 3}), <mekanism:basicblock2:3>.withTag({tier: 3}), <mekanism:basicblock2:3>.withTag({tier: 3})]]);
recipes.addShaped(<icbmclassic:explosives:15>, [[<icbmclassic:explosives:13>, <computercraft:computer>, <icbmclassic:explosives:13>],[<minecraft:nether_star>, <ic2:te:22>, <minecraft:nether_star>], [<appliedenergistics2:material:47>, <extrautils2:unstableingots>, <appliedenergistics2:material:47>]]);
recipes.addShaped(<industrialforegoing:mob_duplicator>, [[<industrialforegoing:pink_slime_ingot>, <enderio:block_experience_obelisk>, <industrialforegoing:pink_slime_ingot>],[<mekanism:basicblock2:4>.withTag({tier: 3}), <extrautils2:compressedcobblestone:5>, <mekanism:basicblock2:3>.withTag({tier: 2})], [<enderio:item_material:55>, <enderio:block_dark_steel_anvil>, <enderio:item_material:55>]]);
recipes.addShaped(<enderio:block_powered_spawner>, [[<openmodularturrets:turret_base:4>, <enderio:item_material:55>, <openmodularturrets:turret_base:4>],[<enderio:item_material:41>, <industrialforegoing:mob_duplicator>, <minecraft:elytra>], [<witchery:flowing_spirit_brew>, <industrialforegoing:mob_duplicator>, <witchery:flowing_spirit_brew>]]);
recipes.addShaped(<extrautils2:quarry>, [[<mekanism:basicblock2:4>.withTag({tier: 3}), <appliedenergistics2:controller>, <mekanism:basicblock2:3>.withTag({tier: 3})],[<enderio:block_transceiver>, <appliedenergistics2:quantum_link>, <enderio:block_transceiver>], [<mekanism:basicblock2:3>.withTag({tier: 3}), <compactvoidminers:void_miner>, <mekanism:basicblock2:4>.withTag({tier: 3})]]);
recipes.addShaped(<extrautils2:quarryproxy>, [[<openmodularturrets:turret_base:4>, <appliedenergistics2:quantum_ring>, <extrautils2:teleporter:1>],[<enderio:item_material:66>, <witchery:otherwhere_spirit>, <botania:blackholetalisman>], [<openmodularturrets:turret_base:4>, <appliedenergistics2:quantum_ring>, <extrautils2:teleporter:1>]]);
recipes.addShaped(<gravisuite:vajra>, [[<appliedenergistics2:controller>, <appliedenergistics2:material:38>, <appliedenergistics2:material:38>],[<appliedenergistics2:dense_energy_cell>, <botania:lens:6>, <ic2:energy_crystal>], [<mekanism:atomicdisassembler>, <powersuits:power_fist>, <gravisuite:crafting:5>]]);
recipes.addShaped(<mekanism:atomicdisassembler>, [[<redstonearsenal:tool.pickaxe_flux>, <mekanism:energycube>.withTag({tier: 3}), <redstonearsenal:tool.sword_flux>],[<redstonearsenal:tool.shovel_flux>, <enderio:item_material:73>, <redstonearsenal:tool.axe_flux>], [<simplyjetpacks:metaitemmods:12>, <enderio:item_material:54>, <simplyjetpacks:metaitemmods:12>]]);
recipes.addShaped(<extrautils2:angelring>, [[<botania:pylon:2>, <witchery:subdued_spirit>, <botania:pylon:2>],[<extrautils2:unstableingots>, <botania:pixiering>, <extrautils2:unstableingots>], [null, <botania:rune:3>, null]]);
recipes.addShaped(<enderio:block_tele_pad>, [[<mekanism:machineblock:11>, <openmodularturrets:turret_base:4>, <mekanism:machineblock:11>],[<enderio:item_material:54>, <computercraft:computer:16384>, <enderio:item_material:54>], [<mekanism:basicblock:8>, <ic2:te:39>, <mekanism:basicblock:8>]]);
recipes.addShaped(<industrialforegoing:laser_base>, [[<appliedenergistics2:material:38>, <mekanism:energycube>.withTag({tier: 3}), <thermaldynamics:duct_0:5>],[<enderio:item_material:54>, <mekanism:machineblock2:14>, <enderio:item_material:54>], [<simplyjetpacks:metaitemmods:23>, <openmodularturrets:turret_base:3>, <simplyjetpacks:metaitemmods:23>]]);
recipes.addShaped(<industrialforegoing:laser_drill>, [[<enderio:item_material:53>, <thermalfoundation:upgrade:3>, <mekanism:transmitter:6>],[<simplyjetpacks:itemfluxpack:9>, <redstonearsenal:tool.pickaxe_flux>, <mekanism:machineblock2:13>], [<enderio:item_material:54>, <mekanism:machineblock3>, <mekanism:transmitter>]]);
recipes.addShaped(<mekanism:machineblock:4>, [[<enderio:block_dark_steel_anvil>, <appliedenergistics2:material:47>, <enderio:block_dark_steel_anvil>],[<mekanism:basicblock2:4>.withTag({tier: 3}), <appliedenergistics2:material:38>, <mekanism:basicblock2:3>.withTag({tier: 3})], [<thermalinnovation:saw:4>, <mekanism:machineblock3>, <thermalinnovation:drill:4>]]);
//File End
